### DC DATA ###
### MUST MATCH HOSTS FILE HIERARCHY
dc_name: dc01

### SPINES ###
l3spine:
  ### DEFAULTS APPLY TO ALL NODES DEFINED UNDER THE 'NODES' KEY BUT ARE OVERRIDEN IF THE SAME VALUES ARE DEFINED ON THE NODE
  defaults:
    platform: VEOS-LAB
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.0.2.0/24
    mlag: true
    mlag_peer_l3_ipv4_pool: 10.0.12.0/24
    mlag_peer_ipv4_pool: 192.168.1.0/24
    mlag_interfaces: [Ethernet47, Ethernet48]
    virtual_router_mac_address: 00:1c:73:00:dc:01
  node_groups:
    - group: sp
      nodes:
        - name: sp01
          ### IDS ARE USED FOR IP ADDRESSING AND OTHER AVD ALGORITHMS
          id: 1
          mgmt_ip: 192.168.0.173/24
        - name: sp02
          id: 2
          mgmt_ip: 192.168.0.174/24

### LEAFS ###
leaf:
  ### DEFAULTS APPLY TO ALL NODES DEFINED UNDER THE 'NODES' KEY BUT ARE OVERRIDEN IF THE SAME VALUES ARE DEFINED ON THE NODE
  defaults:
    platform: VEOS-LAB
    ### LEAF PORTS USED TO CONNECT TO SPINES ###
    ### THE CONNECTIONS BELOW ARE A MATRIX - ALL LEAFS WILL CONNECT TO SPINES ON PORT ETH1 TO SP01 ###
    uplink_interfaces: [Ethernet1, Ethernet2]
    uplink_switches: [sp01, sp02]
    ### USED TO RESERVE IP ADDRESSES FOR FUTURE ADDITIONS - SET TO 8 SPINES ###
    max_uplink_switches: 3
    mlag: true
    mlag_peer_ipv4_pool: 192.168.1.0/24
    mlag_interfaces: [Ethernet47, Ethernet48]
    ### VIRTUAL ROUTE MAC ADDRESS FOR ANYCAST GATEWAYS ###
    ### BELOW IS AN ARISTA WELL KNOWN VALUE ###
    virtual_router_mac_address: 00:1c:73:00:00:99
  ### DEFINTION OF SWITCHES SPECIFIC VALUES ###
  ### DEFAULT + SPECIFIC ###
  node_groups:
    - group: le01
      filter:
        tags: [ common ]
      nodes:
        - name: le01a
          id: 3
          uplink_switch_interfaces: ['Ethernet1', 'Ethernet1']
          mgmt_ip: 192.168.0.175/24
        - name: le01b
          id: 4
          uplink_switch_interfaces: ['Ethernet2', 'Ethernet2']
          mgmt_ip: 192.168.0.176/24
    - group: le02
      filter:
        tags: [ common ]
      nodes:
        - name: le02a
          id: 5
          uplink_switch_interfaces: ['Ethernet3', 'Ethernet3']
          mgmt_ip: 192.168.0.177/24
        - name: le02b
          id: 6
          uplink_switch_interfaces: ['Ethernet4', 'Ethernet4']
          mgmt_ip: 192.168.0.178/24
    - group: bl01
      filter:
        tags: [ border ]
      nodes:
        - name: bl01a
          id: 7
          uplink_switch_interfaces: ['Ethernet5', 'Ethernet5']
          mgmt_ip: 192.168.0.179/24
        - name: bl01b
          id: 8
          uplink_switch_interfaces: ['Ethernet6', 'Ethernet6']
          mgmt_ip: 192.168.0.180/24