all:
  children:
    acme_fabric:
      children:
        dc01:
          children:
            dc01_leaf:
              hosts:
                bl01a: null
                bl01b: null
                le01a: null
                le01b: null
                le02a: null
                le02b: null
              vars:
                type: leaf
            dc01_spine:
              hosts:
                sp01: null
                sp02: null
              vars:
                type: l3spine
        servers:
          hosts:
            server17:
              vars:
                srv_gw: 10.4.40.1
                srv_ip: 10.4.40.117
            server18:
              vars:
                srv_gw: 10.4.41.1
                srv_ip: 10.4.41.118
            server19:
              vars:
                srv_gw: 10.4.40.1
                srv_ip: 10.4.41.119
            server20:
              vars:
                srv_gw: 10.4.41.1
                srv_ip: 10.4.41.120
            server21:
              vars:
                srv_gw: 10.5.50.1
                srv_ip: 10.5.50.121
            server22:
              vars:
                srv_gw: 10.5.51.1
                srv_ip: 10.5.51.122
            server23:
              vars:
                srv_gw: 10.5.50.1
                srv_ip: 10.5.50.123
            server24:
              vars:
                srv_gw: 10.5.51.1
                srv_ip: 10.5.51.124
                srv_vlan: 44
          vars:
            type: server
      vars:
        ansible_become: true
        ansible_become_method: enable
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_network_os: eos
        ansible_ssh_pass: arista1234
        ansible_user: cvpadmin
    cvp:
      hosts:
        cv_server:
          ansible_connection: httpapi
          ansible_host: 10.18.163.193
          ansible_httpapi_host: 10.18.163.193
          ansible_httpapi_port: 443
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_user: svc_account
          ansible_password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjczNjczODgwMTY4MDI3OTE2MDYsImRzbiI6ImN2cGFwaSIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NDYxMTUxMjcsImlhdCI6MTcxNTM1NjczMywib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiNDlmZTc3ZTZmZDhmYTExZmFlMWQzNWM5MzA1MjQ1NDY1OTM3YTk3OTUxMDdhOTQ4NGEyZDcxYTE2YTc3OThhNC1Yb0M5b2JYRVg4bERWcVE2S0Ewd0NYNmFFY3FIVnN3YTM2M0dLNFQ4In0.g0FOp0_CdRhvflQFU5tu5cxngLGzGcaUIwY5Ym_5iggJmBB5mDjZ_asxvZszjHjJHoyBPgRHDnzD-0yeE74Ha5EIRpgrw9qnvtqZdP-uohgu3rTN3Z8z3kpQ2YkuctpSIdyYV2tza6KwYVUwB0PBnjBnqxmg84sOqjNdqvaQKoyFpxzwIjW8gUyoFXb-XWg390kdftv5BoKlz1zgMbVP-8tkl_kF8wsI1tefzVMZRNw4__L0hFrc7Pi0-uJj84yfd4Uo8D_Dq8YeZzpoBk9Yfo57n5Ft2QdGW-xKcC4ctyGMnEOy6HB9ds8IIhZ_WQ7ToDqGS_PpxVHM31VJwLeVWdpF4BBgcDp1AxqqG4SHa2Fv2GZ91jRSDLay_W1BwsVfuxrdphyAJZ0hJswQyF-8vNMTdsVLr9u5ruxKRU6LH8WH7dRebFW8a7Yq9NlaxQoP8Cz0U-mQelBBI1lF0prbl2wjeb1YGcIGNz-6GQyaIwYC6FlqWpufy1-OlHbIQgWrKuHX-AN85TxgVoYyZ_hZhvkuju4JcinzxCh7qUsvhgx9cfjvRzmTsUBoCkYWtv39QZHTPn9rGhKB8A3Wl2vjy4fOmfBto9lK7-mVJnSXlcsxcvNy4ychbKGhQVtQeorUk1Xvy6IT1dCchA6v0gVASrLbq4lGSc_PtEhDZEVNKck
    dc01_compute:
      children:
        dc01_leaf: null
    dc01_nw_services:
      hosts:
        le01a: null
        le01b: null
        le02a: null
        le02b: null
        sp01: null
        sp02: null
  vars:
    ansible_python_interpreter: python3
